config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :tasks do
    post '/assignments', to: 'task_assignments#create', as: 'assignment'
    delete '/assignments', to: 'task_assignments#destroy'
  end
  resources :users, only: [:show, :edit, :update]
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :creator, class_name: "User", foreign_key: "user_id"
  has_many :task_assignments, dependent: :destroy
  has_many :assignees, through: :task_assignments

  def assigned_to?(user)
    self.assignees.include?(user)
  end

  def owned_by?(user)
    self.creator == user
  end
end

app/models/task_assignment.rb
class TaskAssignment < ActiveRecord::Base
  belongs_to :assignee, class_name: "User", foreign_key: "user_id"
  belongs_to :assignment, class_name: "Task", foreign_key: "task_id"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tasks
  has_many :task_assignments, dependent: :destroy
  has_many :assignments, through: :task_assignments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/task_assignments_controller.rb
class TaskAssignmentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @task = Task.find(params[:task_id])
    @user = User.find(params[:user])
    @assignment = TaskAssignment.new(assignee: @user, assignment: @task)

    if @assignment.save
      redirect_to task_path(@task), :notice => "Your task has been successfully assigned to #{@user.email}"
    else
      redirect_to task_path(@task), :alert => "Task could not be assigned."
    end
  end

  def destroy
    @task = Task.find(params[:task_id])
    user = User.find(params[:user])
    assignment = TaskAssignment.find_by(assignment: @task, assignee: user)

    TaskAssignment.destroy(assignment)
    redirect_to task_path(@task), :notice => "Task has been unassigned."
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params.merge! creator: current_user)

    if @task.save
      redirect_to tasks_path, :notice => "Your task was successfully created."
    else
      redirect_to new_task_path, :alert => "Your task could not be saved. Make sure all fields are filled out and try again."
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])

    if @task.update_attributes(task_params)
      redirect_to task_path, :notice => "Your task has been updated."
    else
      redirect_to edit_task_path, :alert => "Your task could not be saved. Make sure all fields are filled out and try again."
    end
  end

  def destroy
    task = Task.destroy(params[:id])
    redirect_to tasks_path, :notice => "Your task \"#{task.title}\" has been deleted."
  end

  private

  def task_params
    params.require(:task).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  # def edit
  #   @user = User.find(params[:id])
  # end

  # def update
  #   @user = User.find(params[:id])

  #   if @user.update_attributes(user_params)
  #     redirect_to user_path, :notice => "Your profile information has been updated."
  #   else
  #     redirect_to edit_user_path, :alert => "Your profile information could not be saved. Make sure all fields are filled out and try again."
  #   end
  # end

  # private

  # def user_params
  #   params.require(:user).permit(:email)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_assignments_helper.rb
module TaskAssignmentsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def format_email(email_address)
    return '' unless valid_email?(email_address)
    wbr = "<wbr>"
    prefix, at, suffix = email_address.rpartition("@").reject(&:empty?)
    prefix.gsub!(/(\W)/i){ |char| wbr + char }
    suffix.gsub!(/(\W)/i){ |char| wbr + char }

    (prefix + wbr + at + suffix).html_safe
  end

  def valid_email?(email_address)
    return false unless email_address && email_address.kind_of?(String)
    prefix, at, suffix = email_address.rpartition("@").reject(&:empty?)
    return false if prefix.nil? or suffix.nil?

    true
  end
end

app/views/home/index.html.erb
<p>Hello World!</p>

app/views/layouts/_header.html.erb
<header>
  <div class="row masthead">
    <div class="small-12 columns">

      <div class="row logo-container">
        <h2 class="subtitle column"><strong>PRYNT</strong> | TASK MANAGER</h2>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<div class="row alert-box-row">
  <div class="small-12 columns alert-box-columns">
    <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
            <div data-alert class="alert-box <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
                <a href="#" class="close">&times;</a>
                <%= content_tag :div, msg %>
            </div>
        <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<div class="contain-to-grid sticky">
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1>
        <%= link_to(root_path) do %>
          <span class="hide-for-small">home</span>
          <i class="fa fa-home fa-lg show-for-small"></i>
        <% end %>
        </h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#">menu</a></li>
    </ul>
    <div class="top-bar-section">
      <%= render 'layouts/navigation_links' %>
    </div>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<ul class="right">
  <% if user_signed_in? %>
      <li><%= link_to "My Profile", user_path(current_user), :class => "" %>
      </li>
      <!-- menu items from tabs for small screens -->
      <li class="show-for-small-only">
        <%= link_to "New Task", new_task_path %>
      </li>
      <li class="show-for-small-only">
        <%= link_to "View All Tasks", tasks_path %>
      </li>
      <!-- /menu items from tabs for small screens -->
      <li>
        <%= link_to 'Logout', destroy_user_session_path, :method => :delete %>
      </li>
  <% else %>
      <li>
        <%= link_to 'Login', new_user_session_path %>
      </li>
      <li>
        <%= link_to 'Sign Up', new_user_registration_path, :class => "btn-primary" %>
      </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Prynt | Task Manager" %></title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag    "application", media: "all", 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <script src="https://use.typekit.net/crf0gdd.js"></script>
    <script>try{Typekit.load({ async: true });}catch(e){}</script>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/navigation' %>
    <main role="main">
       <%= render 'layouts/messages' %>
    <%= yield %>

  </body>
</html>

app/views/tasks/edit.html.erb
<div class="row">
<%= simple_form_for @task,
    url: { action: :update, controller: 'tasks'}, :method => :put, validate: true do |f| %>
    <%= f.error_notification %>
    <div class="form-inputs">
    <%= f.input :title, input_html: { value: @task.title || '' } %>
    <%= f.text_area :description, input_html: { value: @task.description || '' } %>
    </div>
    <div class="form-actions">
    <%= f.button :submit, class: "button radius" %>
    </div>
<% end %>
</div>

app/views/tasks/index.html.erb
<div class="row tasks">
    <h1>Tasks List</h1>
    <div class="row">
        
    <%= link_to "+ New Task", new_task_path, class: "button radius" %>
    </div>
    <div class="row">
        
    <% @tasks.each do |task| %>
    <div class="task-item vcard">
        <div class="task-item">
            <h2><%= task.title %></h2>
            <%= link_to "See Details", task_path(task) %>
            <p>Created by <%= task.creator.email %></p>
            </ul>
        </div>
    </div>
    <% end %>
    </div>
</div>

app/views/tasks/new.html.erb
<div class="row">
<%= simple_form_for @task do |f| %>
    <%= f.error_notification %>
    <div class="form-inputs">
    <%= f.input :title %>
    <%= f.text_area :description %>
    </div>
    <div class="form-actions">
    <%= f.button :submit, class: "button radius" %>
    </div>
<% end %>
</div>

app/views/tasks/show.html.erb
<div class="row breadcrumb">
    <div class="column">
        <%= link_to "Return to Tasks List", tasks_path %>
    </div>
</div>

<div class="row task-content-container">
    <div class="columns small-6">
        <h1><%= @task.title %></h1>
        <p><strong>Description</strong></p>
        <%= @task.description %></p>
        <p><em>Created by <%= @task.creator.email %></em></p>
        <% if @task.owned_by?(current_user) or @task.assigned_to?(current_user)%>
        <p><%= link_to "Edit", edit_task_path(@task) %></p>
        <% end %>
        <p>

        <% if @task.owned_by?(current_user) %>
        <p><%= button_to "Delete",
            { action: "destroy" },
                method: :delete,
                data: { confirm: "Are you sure?" },
                class: "button radius alert" %></p>
        <% end %>
    </div>
    <% if @task.assigned_to?(current_user) %>
    <%= button_to "Remove Me From Assignment", task_assignments_path(task_id: @task.id, user: current_user), method: :delete, class: "button radius" %>
    <% else %>
    <%= button_to "Assign To Me", task_assignment_path(task_id: @task, user: current_user), class: "button radius" %>
    <% end %>
<div class="columns small-6 panel">
    <h2><small>Assigned to</small></h2>
    <% if @task.assignees.empty? %>
    <p>Task is not yet assigned to anyone</p>
    <% end %>
    <ul>
    <% @task.assignees.each do |assignee| %>
    <li><%= assignee.email %></li>
    <% end %>
    </ul>
</div>
</div>

app/views/users/show.html.erb
<div class="row">    
<h3>Account Settings</h3>
<table class="12-large columns">
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= format_email(@user.email.downcase) %></td>
        <td><%= link_to "Change Email / Password", edit_user_registration_path %></td>
      </tr>
  </tbody>
</table>
<%= link_to "Delete Account", edit_user_registration_path %>
</div>